# Generated by Django 3.1.2 on 2020-11-26 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201101_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='starting_weight',
        ),
    ]
