# Generated by Django 3.1.2 on 2020-11-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201101_0536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='starting_weight',
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.IntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.DecimalField(decimal_places=1, default=1.5, max_digits=2),
        ),
        migrations.AlterField(
            model_name='profile',
            name='daily_cal_in',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='daily_carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='daily_fat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='daily_protein',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal_weight_change',
            field=models.IntegerField(default=-1),
        ),
    ]
