# Generated by Django 3.1.2 on 2020-11-15 22:53

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201115_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.DecimalField(decimal_places=1, default=1.5, help_text='Must be a value betwen 1.2 and 2.1', max_digits=2, validators=[users.models.validate_activity_level]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal_weight_change',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=3, validators=[users.models.validate_goal_weight_change]),
        ),
    ]
