# Generated by Django 3.1.2 on 2020-11-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201115_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pct_diet_carbs',
            field=models.IntegerField(default=45),
        ),
        migrations.AddField(
            model_name='profile',
            name='pct_diet_fat',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='pct_diet_prot',
            field=models.IntegerField(default=35),
        ),
    ]
