# Generated by Django 3.1.2 on 2020-11-27 23:34

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201115_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=0, validators=[users.models.validate_not_neg]),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbs',
            field=models.IntegerField(validators=[users.models.validate_not_neg]),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.IntegerField(validators=[users.models.validate_not_neg]),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.IntegerField(validators=[users.models.validate_not_neg]),
        ),
        migrations.AlterField(
            model_name='liftrecord2',
            name='reps',
            field=models.IntegerField(blank=True, help_text='Cannot be negative', null=True, validators=[users.models.validate_not_neg]),
        ),
        migrations.AlterField(
            model_name='liftrecord2',
            name='sets',
            field=models.IntegerField(blank=True, help_text='Cannot be negative', null=True, validators=[users.models.validate_not_neg]),
        ),
        migrations.AlterField(
            model_name='liftrecord2',
            name='weight',
            field=models.IntegerField(blank=True, help_text='Cannot be negative', null=True, validators=[users.models.validate_not_neg]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='activity_level',
            field=models.DecimalField(decimal_places=1, default=1.5, help_text='Must be a value between 1.2 and 2.1', max_digits=2, validators=[users.models.validate_activity_level]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='goal_weight_change',
            field=models.DecimalField(decimal_places=2, default=-1, help_text='Must be a value between -1 and 1', max_digits=3, validators=[users.models.validate_goal_weight_change]),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='lbs',
            field=models.IntegerField(help_text='May not be a negative number.', validators=[users.models.validate_not_neg]),
        ),
    ]
