# Generated by Django 3.1.2 on 2020-11-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201127_2334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LiftRecord',
        ),
    ]
