# Generated by Django 3.1.2 on 2020-11-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201127_2346')
    ]

    operations = [
    ]
