# Generated by Django 3.1.2 on 2020-11-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_20201128_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='liftrecord',
            name='one_rep_max_equiv',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
